spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: asus
    password: asus
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
server:
  port: 8080
